# Generated by Django 5.2.13 on 2026-04-20 13:06

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickName', models.CharField(blank=True, max_length=150, verbose_name='用户名')),
                ('avatarUrl', models.CharField(blank=True, max_length=500, verbose_name='头像')),
                ('trueName', models.CharField(blank=True, max_length=150, verbose_name='真实姓名')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('gender', models.IntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], default=0, verbose_name='性别')),
                ('wxapp_openid', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='微信小程序openid')),
                ('wxh5_openid', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='微信公众号openid')),
                ('bdapp_openid', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='百度小程序openid')),
                ('is_h5', models.BooleanField(default=False, verbose_name='H5用户')),
                ('is_app', models.BooleanField(default=False, verbose_name='APP用户')),
                ('is_pc', models.BooleanField(default=False, verbose_name='PC用户')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, unique=True, verbose_name='手机号')),
                ('regtime', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('last_time', models.DateTimeField(blank=True, null=True, verbose_name='最后活跃时间')),
                ('state', models.IntegerField(choices=[(0, '拉黑'), (1, '游客'), (2, '用户')], default=2, verbose_name='用户状态')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('pid', models.IntegerField(default=0, verbose_name='上级id')),
                ('is_distributor', models.IntegerField(choices=[(1, '普通用户'), (2, '审核中分销商'), (3, '审核通过分销商'), (4, '审核拒绝分销商')], default=1, verbose_name='分销商状态')),
                ('uniacid', models.IntegerField(default=0, verbose_name='平台id')),
                ('unionid', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='开放平台唯一标识')),
                ('is_user', models.IntegerField(default=0, verbose_name='是否有用户信息')),
                ('lid', models.IntegerField(default=0, verbose_name='标签id')),
                ('token', models.CharField(blank=True, max_length=255, verbose_name='token')),
                ('bind_time', models.DateTimeField(blank=True, null=True, verbose_name='与分销商绑定时间')),
                ('wxstore_openid', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='微信小店openid')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
